// <auto-generated />
using System;
using HireAI.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HireAI.Infrastructure.Migrations
{
    [DbContext(typeof(HireAIDbContext))]
    partial class HireAIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HireAI.Data.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId1")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.HasIndex("QuestionId", "IsCorrect");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("HireAI.Data.Models.ApplicantResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExamSummaryId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamSummaryId");

                    b.HasIndex("ExamSummaryId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ApplicantResponses", t =>
                        {
                            t.HasCheckConstraint("CK_ApplicantResponse_Answer", "[AnswerNumber] > 0");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.ApplicantSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<float?>("SkillRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicantSkills", t =>
                        {
                            t.HasCheckConstraint("CK_ApplicantSkill_Rate", "([SkillRate] >= 0 AND [SkillRate] <= 100) OR [SkillRate] IS NULL");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<string>("CVFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("HRId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<float?>("ScoreATS")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationStatus");

                    b.HasIndex("HRId");

                    b.HasIndex("JobId");

                    b.HasIndex("ApplicantId", "JobId")
                        .IsUnique();

                    b.ToTable("Applications", t =>
                        {
                            t.HasCheckConstraint("CK_Application_Score", "([ScoreATS] >= 0 AND [ScoreATS] <= 100) OR [ScoreATS] IS NULL");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Experience")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GitHubPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkedInPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("YearsOfExperience")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.ToTable("CVs", t =>
                        {
                            t.HasCheckConstraint("CK_CV_YearsOfExperience", "[YearsOfExperience] >= 0 OR [YearsOfExperience] IS NULL");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("ApplicantId", "CreatedAt");

                    b.ToTable("Exams", t =>
                        {
                            t.HasCheckConstraint("CK_Exam_Duration", "[DurationInMinutes] > 0");

                            t.HasCheckConstraint("CK_Exam_NumberOfQuestions", "[NumberOfQuestions] > 0");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.ExamEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamSummaryId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<float>("MaxTotal")
                        .HasColumnType("real");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExamSummaryId")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.ToTable("ExamEvaluation", t =>
                        {
                            t.HasCheckConstraint("CK_ExamEvaluation_Scores", "[TotalScore] >= 0 AND [MaxTotal] > 0 AND [TotalScore] <= [MaxTotal]");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.ExamSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ExamEvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExamEvaluationId")
                        .IsUnique()
                        .HasFilter("[ExamEvaluationId] IS NOT NULL");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamSummarys");
                });

            modelBuilder.Entity("HireAI.Data.Models.JobOpening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ATSMinimumScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int?>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int?>("ExamDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<int>("HRId")
                        .HasColumnType("int");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("HRId");

                    b.ToTable("JobOpenings", t =>
                        {
                            t.HasCheckConstraint("CK_JobOpening_ATSScore", "([ATSMinimumScore] >= 0 AND [ATSMinimumScore] <= 100) OR [ATSMinimumScore] IS NULL");

                            t.HasCheckConstraint("CK_JobOpening_ExamDuration", "[ExamDurationMinutes] > 0 OR [ExamDurationMinutes] IS NULL");

                            t.HasCheckConstraint("CK_JobOpening_Questions", "[NumberOfQuestions] > 0 OR [NumberOfQuestions] IS NULL");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.HasIndex("JobId", "SkillId")
                        .IsUnique();

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("HireAI.Data.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeTo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payment_Currency", "LEN([Currency]) = 3");
                        });
                });

            modelBuilder.Entity("HireAI.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Answer")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicantResponseId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantResponseId")
                        .IsUnique()
                        .HasFilter("[ApplicantResponseId] IS NOT NULL");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("HireAI.Data.Models.QuestionEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantResponseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ExamEvaluationId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicantResponseId")
                        .IsUnique();

                    b.HasIndex("ExamEvaluationId", "ApplicantResponseId");

                    b.ToTable("QuestionEvaluations");
                });

            modelBuilder.Entity("HireAI.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Siklls");
                });

            modelBuilder.Entity("HireAI.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Free");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HireAI.Data.Models.Applicant", b =>
                {
                    b.HasBaseType("HireAI.Data.Models.User");

                    b.Property<int>("CVId")
                        .HasColumnType("int");

                    b.Property<int?>("JobOpeningId")
                        .HasColumnType("int");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasIndex("CVId")
                        .IsUnique()
                        .HasFilter("[CVId] IS NOT NULL");

                    b.HasIndex("JobOpeningId");

                    b.ToTable("Applicant", (string)null);
                });

            modelBuilder.Entity("HireAI.Data.Models.HR", b =>
                {
                    b.HasBaseType("HireAI.Data.Models.User");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PremiumExpiry")
                        .HasColumnType("datetime2");

                    b.HasIndex("AccountType");

                    b.HasIndex("CompanyName");

                    b.ToTable("HRs", (string)null);
                });

            modelBuilder.Entity("HireAI.Data.Models.Answer", b =>
                {
                    b.HasOne("HireAI.Data.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId1");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HireAI.Data.Models.ApplicantResponse", b =>
                {
                    b.HasOne("HireAI.Data.Models.ExamSummary", "ExamSummary")
                        .WithMany()
                        .HasForeignKey("ExamSummaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSummary");
                });

            modelBuilder.Entity("HireAI.Data.Models.ApplicantSkill", b =>
                {
                    b.HasOne("HireAI.Data.Models.Applicant", "Applicant")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.Skill", "Skill")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HireAI.Data.Models.Application", b =>
                {
                    b.HasOne("HireAI.Data.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.HR", "HR")
                        .WithMany("Applications")
                        .HasForeignKey("HRId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.JobOpening", "AppliedJob")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("AppliedJob");

                    b.Navigation("HR");
                });

            modelBuilder.Entity("HireAI.Data.Models.Exam", b =>
                {
                    b.HasOne("HireAI.Data.Models.Applicant", "Applicant")
                        .WithMany("Exams")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.Application", "Application")
                        .WithOne("Exam")
                        .HasForeignKey("HireAI.Data.Models.Exam", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HireAI.Data.Models.ExamEvaluation", b =>
                {
                    b.HasOne("HireAI.Data.Models.JobOpening", "JobOpening")
                        .WithMany("ExamEvaluations")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobOpening");
                });

            modelBuilder.Entity("HireAI.Data.Models.ExamSummary", b =>
                {
                    b.HasOne("HireAI.Data.Models.Applicant", null)
                        .WithMany("ExamSummarys")
                        .HasForeignKey("ApplicantId");

                    b.HasOne("HireAI.Data.Models.Application", "Application")
                        .WithOne("ExamSummary")
                        .HasForeignKey("HireAI.Data.Models.ExamSummary", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.ExamEvaluation", "ExamEvaluation")
                        .WithOne("ExamSummary")
                        .HasForeignKey("HireAI.Data.Models.ExamSummary", "ExamEvaluationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HireAI.Data.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Exam");

                    b.Navigation("ExamEvaluation");
                });

            modelBuilder.Entity("HireAI.Data.Models.JobOpening", b =>
                {
                    b.HasOne("HireAI.Data.Models.HR", "HR")
                        .WithMany("HRJobs")
                        .HasForeignKey("HRId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("HireAI.Data.Models.JobSkill", b =>
                {
                    b.HasOne("HireAI.Data.Models.JobOpening", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HireAI.Data.Models.Payment", b =>
                {
                    b.HasOne("HireAI.Data.Models.HR", "HR")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("HireAI.Data.Models.Question", b =>
                {
                    b.HasOne("HireAI.Data.Models.ApplicantResponse", "ApplicantResponse")
                        .WithOne("Question")
                        .HasForeignKey("HireAI.Data.Models.Question", "ApplicantResponseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HireAI.Data.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantResponse");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("HireAI.Data.Models.QuestionEvaluation", b =>
                {
                    b.HasOne("HireAI.Data.Models.ApplicantResponse", "ApplicantResponse")
                        .WithOne("QuestionEvaluation")
                        .HasForeignKey("HireAI.Data.Models.QuestionEvaluation", "ApplicantResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.ExamEvaluation", "ExamEvaluation")
                        .WithMany("QuestionEvaluations")
                        .HasForeignKey("ExamEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantResponse");

                    b.Navigation("ExamEvaluation");
                });

            modelBuilder.Entity("HireAI.Data.Models.Applicant", b =>
                {
                    b.HasOne("HireAI.Data.Models.CV", "CV")
                        .WithOne("Applicant")
                        .HasForeignKey("HireAI.Data.Models.Applicant", "CVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HireAI.Data.Models.Applicant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireAI.Data.Models.JobOpening", null)
                        .WithMany("Applicants")
                        .HasForeignKey("JobOpeningId");

                    b.Navigation("CV");
                });

            modelBuilder.Entity("HireAI.Data.Models.HR", b =>
                {
                    b.HasOne("HireAI.Data.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HireAI.Data.Models.HR", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HireAI.Data.Models.ApplicantResponse", b =>
                {
                    b.Navigation("Question")
                        .IsRequired();

                    b.Navigation("QuestionEvaluation");
                });

            modelBuilder.Entity("HireAI.Data.Models.Application", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();

                    b.Navigation("ExamSummary");
                });

            modelBuilder.Entity("HireAI.Data.Models.CV", b =>
                {
                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("HireAI.Data.Models.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HireAI.Data.Models.ExamEvaluation", b =>
                {
                    b.Navigation("ExamSummary")
                        .IsRequired();

                    b.Navigation("QuestionEvaluations");
                });

            modelBuilder.Entity("HireAI.Data.Models.JobOpening", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("Applications");

                    b.Navigation("ExamEvaluations");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("HireAI.Data.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("HireAI.Data.Models.Skill", b =>
                {
                    b.Navigation("ApplicantSkills");
                });

            modelBuilder.Entity("HireAI.Data.Models.Applicant", b =>
                {
                    b.Navigation("ApplicantSkills");

                    b.Navigation("Applications");

                    b.Navigation("ExamSummarys");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("HireAI.Data.Models.HR", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("HRJobs");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
